config/routes.rb
Rails.application.routes.draw do
  root :to => 'users#index'
  resources :user_sessions
  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
  resources :posts

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  # app/controllers/user_sessions_controller.rb
  skip_before_action :require_login, except: [:destroy]

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(:posts, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:users, notice: 'Logged out!')
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field form-group">
    <%= label_tag :email %><br />
    <%= text_field_tag :email ,nil ,class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= label_tag :password %><br />
    <%= password_field_tag :password ,nil ,class: "form-control" %>
  </div>
  <div class="actions">
    <%= submit_tag "登录" , class: "btn btn-default" %>
  </div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">

<h1>Login</h1>

<%= render 'form' %>

</div>
</div>